# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe"
CFLAGS="-march=native ${COMMON_FLAGS}"
CXXFLAGS="${CFLAGS}"
LDFLAGS="${LDFLAGS} -fuse-ld=mold"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# NOTE: This stage was built with the bindist Use flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.utf8

#PYTHON_SINGLE_TARGET=python3_11

# Appending getbinpkg to the list of values within the FEATURES variable
FEATURES="installsources getbinpkg binpkg-request-signature "
ACCEPT_LICENSE="*"
USE="dist-kernel -systemd X elogind man pulseaudio screencast dbus bluetooth xinerama v4l libv4l"
VIDEO_CARDS="amdgpu radeonsi"
L10N="en"
CONFIG_PROTECT_MASK="/etc/portage"
GENTOO_MIRRORS="https://mirror.leaseweb.com/gentoo/ \
    https://mirrors.ircam.fr/pub/gentoo-distfiles/ \
    ftp://ftp.free.fr/mirrors/ftp.gentoo.org/ \
    https://ftp.halifax.rwth-aachen.de/gentoo/ \
    https://mirror.bytemark.co.uk/gentoo/ \
    http://tux.rainside.sk/gentoo/ \
    http://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/"
