# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/steam-overlay.git

[gentoo-zh]
location = /var/db/repos/gentoo-zh
sync-type = git
sync-uri = https://github.com/gentoo-mirror/gentoo-zh.git

[pg_overlay]
location = /var/db/repos/pg_overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/pg_overlay.git

[hossie]
location = /var/db/repos/hossie
sync-type = git
sync-uri = https://github.com/gentoo-mirror/hossie.git
