- hosts: all
  - name: Set up user
    user:
      name: jcomcl
      group: wheel
      create_home: true
      shell: /bin/zsh

  - name: basics for comfortable terminal usage
    package:
      name:
        - doas
        - zsh
        - lf #this one is masked on gentoo
        - kakoune #masked too, smh
        - htop
        - yadm
      state: latest

  - name: doas setup
    lineinfile:
      create: true
      line: 'permit nopass :wheel'
      path: /etc/doas.conf
      validate: 'doas -C %s'

