- name: Create Admin
  user:
      name: adm
      comment: Administrator
      group: wheel
      shell: "/bin/bash"
      create_home: false

- name: Disable SSH password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#? *PasswordAuthentication .*"
    line: "PasswordAuthentication no"
    validate: "sshd -f %s -T"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#? *PermitRootLogin .*"
    line: "PermitRootLogin prohibit-password"
    validate: "sshd -f %s -T"
  register: sshd_config

- name: Restart SSHD
  service:
      name: sshd
      state: restarted
  when: sshd_config.changed
